name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    secrets: inherit
  # helm:
  #   uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main
  #   with: 
  #     buildContext:  "deployment/helm"
  #     harbor_config: "deployment/harbor.config"